### PR TITLE
Avoid Cache

### PR DESCRIPTION
**Pull request by edumco**
### Cache can be completed disabled on alpine linux

The option `no-cache` on `apk add` command disable completely the use of cache during apk installation.

It does not read from nor write to. This command was created for use in containers.

This also removes the need for cleaning things after installation. 

Also it's not necessary to declare use root user if no other used was previous declared.

### CODE REVIEW

**Comment by saidsef** [comment]
@edumco thanks for taking the time and contributing.

I think this is a design style. The essence of cache is to reuse, for example, multiple containers can mount the same cached file system without repeatedly downloading it from the network.

Can view the apline wiki: https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Local_Cache

In any case, I'm happy for this to move forward however it's failing CI - if you could fix that I'll approve it.

**Comment by edumco** [comment]
@saidsef 

There was 2 problems:

- I forgot that Alpine does not run as root :|

- With the `--no-cache` option the `del` command doesn't find the packages to delete.

**Comment by saidsef** [comment]
@edumco 

Hope you've had a good weekend!

The base image subscribes to `jenkins/jeskins` with sandboxes the process with user `jenkins`.

You've removed `apk del` - this removes unused resources and helps reduce the overall image size?

**Comment by edumco** [comment]
HI @saidsef  :dancers: 

> unused resources and helps reduce the overall image size?

Actually no, The docker file system keeps all the files in the layers. 

If you have a package in a layer and you delete in other it will just create a reference saying it was deleted but it wont alter the previous layer.

The only way delete would work is: You added a package and remove in the same run.

Ex:

RUN apk add unzip && unzip somefile.zip && del unzip

In this case during the execution of this RUN command is created a image layer that temporarily has the `unzip` package but the final layer wont have.

Another way you could further reduce the container size is to create the production image from scratch using multistage builds. But I think would be very complex since you're reusing the jenkins/jenkins image.

If the final size is a problem you could create a plugins cache. 

You could replace the plugins folder with some folder on your machine and make the plugin installation, then you remove the plugin installation from the image.

What do you think?

**Comment by saidsef** [comment]
@edumco I hope you are well - and happy Friday 🕺 

Not quite correct, but I take your point - the packages being removed are from a different layer (base image), and removing it at a later stage doesn't change the overall size.

One of the use cases for this container is for air-gaped systems - a platform where egress to internet in order to update/upgrade or installing plugins is not possible - ensuring an idempotent element.

I'm happy with this, I'll merge this if there are no objects?!

**Comment by edumco** [comment]
> Not quite correct, but I take your point - the packages being removed are from a different layer (base image), and removing it at a later stage doesn't change the overall size.

Thats it! I didn't know how to explain that kkkk 

> One of the use cases for this container is for air-gaped systems - a platform where egress to internet in order to update/upgrade or installing plugins is not possible - ensuring an idempotent element.

So in this case is better have all plugins already installed.

Im so happy for helping. This image is well curated. Congrats man!

**Comment by saidsef** [comment]
@edumco sounds good.

I'm going to go ahead and merge - thanks for your time and help.

**Pull request merged**
